// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DCAContext))]
    partial class DCAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DbObjects.FirstSheetItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Col1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtEdit")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("FirstSheetItems");
                });

            modelBuilder.Entity("DAL.DbObjects.SecondSheetItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Col1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAdd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtEdit")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SecondSheetItems");
                });
#pragma warning restore 612, 618
        }
    }
}
